apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quant-finance-pipeline

resources:
- ../../base

patchesStrategicMerge:
- configmap-patch.yaml
- deployment-patch.yaml

configMapGenerator:
- name: app-config
  literals:
  - ENVIRONMENT=development
  - LOG_LEVEL=DEBUG

replicas:
- name: quant-finance-app
  count: 1
- name: quant-finance-dashboard
  count: 1
