apiVersion: apps/v1
kind: Deployment
metadata:
  name: quant-finance-app
  namespace: quant-finance-pipeline
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quant-finance-dashboard
  namespace: quant-finance-pipeline
spec:
  template:
    spec:
      containers:
      - name: dashboard
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
