apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- postgres.yaml
- redis.yaml
- app.yaml
- dashboard.yaml
- scheduler.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: quant-finance-pipeline
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: financial-analytics
