apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: quant-finance-pipeline
type: Opaque
data:
  # Base64 encoded values (replace with actual secrets)
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # "password" in base64
  POSTGRES_USER: cG9zdGdyZXM=      # "postgres" in base64
  POSTGRES_DB: cXVhbnRfZmluYW5jZQ== # "quant_finance" in base64
