name: Data Pipeline

on:
  schedule:
    # Run daily at 6 AM UTC (after market close)
    - cron: '0 6 * * 1-5'
  workflow_dispatch:
    inputs:
      symbols:
        description: 'Comma-separated list of symbols'
        required: false
        default: 'AAPL,GOOGL,MSFT,AMZN,TSLA'

jobs:
  data-collection:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        echo "ALPHA_VANTAGE_API_KEY=${{ secrets.ALPHA_VANTAGE_API_KEY }}" >> $GITHUB_ENV
        echo "QUANDL_API_KEY=${{ secrets.QUANDL_API_KEY }}" >> $GITHUB_ENV
        echo "FRED_API_KEY=${{ secrets.FRED_API_KEY }}" >> $GITHUB_ENV
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> $GITHUB_ENV
    
    - name: Run data collection
      run: |
        python -m src.data_collection.daily_pipeline \
          --symbols "${{ github.event.inputs.symbols || 'AAPL,GOOGL,MSFT,AMZN,TSLA' }}" \
          --upload-to-s3
    
    - name: Upload logs to S3
      if: always()
      run: |
        aws s3 cp logs/ s3://${{ secrets.S3_BUCKET }}/logs/$(date +%Y/%m/%d)/ --recursive

  portfolio-optimization:
    needs: data-collection
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
    
    - name: Run portfolio optimization
      run: |
        python -m src.analytics.portfolio_optimization.daily_optimization
    
    - name: Generate performance report
      run: |
        python -m src.reports.generate_daily_report

  notify-completion:
    needs: [portfolio-optimization]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify pipeline completion
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#data-pipeline'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
      if: always()
